name: pokemon
description: Pokemon App.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: "flutter"

  cupertino_icons: ^1.0.2
  get_it: ^7.1.4
  dio: 4.0.0
  pretty_dio_logger: ^1.1.1
  cached_network_image: ^3.2.0
  rxdart: ^0.27.2
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/subtitles/
    - assets/images/

  fonts:
    - family: RedHatDisplay
      fonts:
        - asset: assets/fonts/RedHatDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/RedHatDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/RedHatDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/RedHatDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/RedHatDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/RedHatDisplay-ExtraBold.ttf
          weight: 900